package pl.michalsnella.mathlearning.model.user;

public enum Achievement {
    LEARN_ADDITION_DONE,
    LEARN_SUBTRACTION_DONE,
    LEARN_MULTIPLICATION_DONE,
    LEARN_DIVISION_DONE,

    PRACTICE_10_TASKS_ANY,
    PRACTICE_10_TASKS_LEVEL_0,
    PRACTICE_10_TASKS_LEVEL_1,
    PRACTICE_10_TASKS_LEVEL_2,
    PRACTICE_10_TASKS_LEVEL_3,
    PRACTICE_10_TASKS_LEVEL_4,

    CHALLENGE_COMPLETED_ANY
}

